# Generated by Django 5.0.6 on 2024-05-29 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CE_Categoria',
            },
        ),
        migrations.CreateModel(
            name='CategoriasMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_de_movimento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CE_Categorias_Movimento',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidade', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.categoria')),
            ],
            options={
                'db_table': 'CE_Produto',
            },
        ),
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.categoriasmovimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.produto')),
            ],
            options={
                'db_table': 'CE_Lancamentos',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contabil_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contabil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primeiro_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.categoriasmovimento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.produto')),
            ],
            options={
                'db_table': 'CE_Estoque',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='ControleEstoque.categoria')),
            ],
            options={
                'db_table': 'CE_SubCategoria',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='sub_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleEstoque.subcategoria'),
        ),
    ]
