# Generated by Django 5.0.6 on 2024-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
