# Generated by Django 5.0.6 on 2024-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_real',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
