# Generated by Django 5.0.6 on 2024-06-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origem',
            old_name='tipo_de_movimento',
            new_name='tipo',
        ),
    ]
