# Generated by Django 5.0.6 on 2024-06-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='contabil',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='contabil_real',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
