# Generated by Django 5.0.6 on 2024-06-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0002_remove_produto_descricao_alter_categoria_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='ce_categoria',
        ),
        migrations.AlterModelTable(
            name='categoriasmovimento',
            table='ce_categorias_movimento',
        ),
        migrations.AlterModelTable(
            name='estoque',
            table='ce_estoque',
        ),
        migrations.AlterModelTable(
            name='lancamentos',
            table='ce_lancamentos',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='ce_produto',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='ce_subcategoria',
        ),
    ]
