# Generated by Django 5.0.6 on 2024-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0002_alter_estoque_contabil_alter_estoque_contabil_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='primeiro_movimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='ultimo_movimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
