# Generated by Django 5.0.6 on 2024-06-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0003_alter_estoque_primeiro_movimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
