# Generated by Django 5.0.6 on 2024-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0003_alter_categoria_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='id',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
