# Generated by Django 5.0.6 on 2024-06-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0005_tipoproduto_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ControleEstoque.tipoproduto'),
            preserve_default=False,
        ),
    ]
