# Generated by Django 5.0.6 on 2024-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0006_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproduto',
            name='id',
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='codigo',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
