# Generated by Django 5.0.6 on 2024-06-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0007_remove_tipoproduto_id_tipoproduto_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasMovimento',
            new_name='Origem',
        ),
        migrations.AlterModelTable(
            name='origem',
            table='ce_origem_lancamento',
        ),
    ]
