# Generated by Django 5.0.6 on 2024-06-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0008_rename_categoriasmovimento_origem_alter_origem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='origem',
            table='ce_origem',
        ),
    ]
