# Generated by Django 5.0.6 on 2024-06-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleEstoque', '0013_rename_categoria_movimento_estoque_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='origem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='origem',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
